name: Build and Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy to gh pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-end

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install dependencies 🌐
        run: npm install

      - name: Run tests 📋
        run: npm test -- --passWithNoTests

      - name: Run build script 🔧
        run: PUBLIC_URL=/kafka-faker/ npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        working-directory: .
        with:
          branch: gh-pages
          folder: front-end/build
